name: linux-amdflang-cmake

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/'
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/'
      - 'AUTHORS.md'
      - 'LICENSE.md'
      - 'README.md'

jobs:
  linux-tests:
    timeout-minutes: 90
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.os }} - ${{ matrix.fcompiler }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
            - os: ubuntu-22.04
              fcompiler: amdflang
              ccompiler: amdclang
              spack_compiler: rocmcc@=6.1.1
              spack_os: "ubuntu:22.04"
              shell: bash
              build_type: debug
              memcheck: false

    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROCm
        run: |
          sudo apt update -y
          wget https://repo.radeon.com/amdgpu-install/6.1.1/ubuntu/jammy/amdgpu-install_6.1.60101-1_all.deb
          sudo apt install -y ./amdgpu-install_6.1.60101-1_all.deb
          sudo amdgpu-install --accept-eula -y --usecase=openmpsdk --no-dkms

      - name: Show version information
        run: |
          export PATH=${PATH}:/opt/rocm/bin
          ${{ matrix.fcompiler }} --version
          ${{ matrix.ccompiler }} --version

      - name: Build with Cmake
        shell: spack-bash {0}
        run: |
          export PATH=${PATH}:/opt/rocm/bin
          mkdir build
          cd build
          FC=${{ matrix.fcompiler }} CC=${{ matrix.ccompiler }} \
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DSELF_MPIEXEC_NUMPROCS=2 \
                ../
          make -j $(nproc) VERBOSE=1

      - name: Run ctests
        run: |
          export WORKSPACE=/home/runner/work/SELF/SELF/
          ctest --verbose \
                --output-on-failure \
                --test-dir ./build/
